[build]
  base = "/"
  command = "npm install @craco/craco && npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 